import '../styles/globals.css'
import {Providers} from "./providers";
import {Navigation} from "../components/Navigation";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body>
            <Providers>
                <Navigation />
                {children}
            </Providers>
        </body>
    </html>
  )
}
